FROM golang:1.17-alpine

RUN mkdir /test

ADD . /test

WORKDIR /test

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN go build -o main .

EXPOSE 8085

CMD [ "/test/main" ]
